version: '3.6'

services:
  db:
    # image: mariadb
    image: jbergstroem/mariadb-alpine
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ=${MYSQL_TZ}
    expose:
      - ${MYSQL_PORT}
  adminer:
    image: adminer
    ports:
      - 8080:8080
  
