version: '3.6'

services:
  db:
    image: mariadb
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ=${MYSQL_TZ}
    expose:
      - ${MYSQL_PORT}
